# Generated by Django 5.1.5 on 2025-02-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_last_name_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
