# Generated by Django 5.1.5 on 2025-02-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_category_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
