# Generated by Django 5.1.5 on 2025-02-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
