# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 200))
        MainWindow.setMaximumSize(QtCore.QSize(800, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.input_cpf = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.input_cpf.setFont(font)
        self.input_cpf.setObjectName("input_cpf")
        self.gridLayout.addWidget(self.input_cpf, 0, 1, 1, 1)
        self.btn_validate_cpf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_validate_cpf.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.btn_validate_cpf.setFont(font)
        self.btn_validate_cpf.setObjectName("btn_validate_cpf")
        self.gridLayout.addWidget(self.btn_validate_cpf, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.btn_generate_cpf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.btn_generate_cpf.setFont(font)
        self.btn_generate_cpf.setObjectName("btn_generate_cpf")
        self.gridLayout.addWidget(self.btn_generate_cpf, 1, 1, 1, 1)
        self.return_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(40)
        self.return_label.setFont(font)
        self.return_label.setStyleSheet("color: green;")
        self.return_label.setText("")
        self.return_label.setAlignment(QtCore.Qt.AlignCenter)
        self.return_label.setObjectName("return_label")
        self.gridLayout.addWidget(self.return_label, 2, 0, 1, 2)
        self.copy_cpf = QtWidgets.QPushButton(self.centralwidget)
        self.copy_cpf.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.copy_cpf.setFont(font)
        self.copy_cpf.setObjectName("copy_cpf")
        self.gridLayout.addWidget(self.copy_cpf, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPF Check Generator"))
        self.label_2.setText(_translate("MainWindow", "Validar CPF"))
        self.btn_validate_cpf.setText(_translate("MainWindow", "VALIDAR"))
        self.label.setText(_translate("MainWindow", "Gerar CPF"))
        self.btn_generate_cpf.setText(_translate("MainWindow", "GERAR"))
        self.copy_cpf.setText(_translate("MainWindow", "COPIAR CPF"))
