from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILE_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILE_DIR / 'icon.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 600

DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
PRIMARY_COLOR = '#1e81b0'
